CREATE TABLE CUSTOMER
(
CUSTID INT,
CUST_NAME VARCHAR (255),
PHONE_NUMBER VARCHAR (255),
RENTAL_TITLE VARCHAR (255),
RENTED_TIME INT,
DATE_RENTED DATE,
STOREID INT,
PRIMARY KEY (CUSTID)
FOREIGN KEY (STOREID) REFERENCES STORE (STOREID)
)